name: Semantic release

on: 
  push:
    branches: [ master ]
jobs:
  quality:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]
        os: [ubuntu-latest, windows-latest, macOS-11]
    steps:
    - uses: actions/checkout@v2
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      
  publish:
    runs-on: ubuntu-latest
    needs: [quality]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: npm run semantic-release
    
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    
    
